# Generated by Django 5.1.4 on 2025-01-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('engine_size', models.FloatField(default=2.0)),
                ('door_number', models.PositiveIntegerField(default=4)),
            ],
        ),
    ]
