# Generated by Django 5.1.4 on 2025-02-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_remove_car_color_remove_car_door_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saklaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField()),
                ('edited', models.BooleanField(default=False)),
                ('write_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
