# Generated by Django 5.1.5 on 2025-02-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_employee_remove_post_category_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=100)),
                ('publish_date', models.DateField()),
                ('archieved', models.BooleanField()),
                ('write_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
